DescriptionDict = {
"Ticker": "The ticker symbol is a unique series of letters assigned to a security for trading purposes.",
"12-1 Month Momentum %": "The 12-1 Month Momentum % represents the percentage change in a stock's price from twelve months ago to the most recent month end.",
"14-Day RSI": "The 14-Day RSI is a technical momentum indicator that compares the magnitude of recent gains to recent losses.",
"3-Year Average Share Buyback Ratio": "The 3-Year Average Share Buyback Ratio is the average proportion of company shares that have been repurchased over the past three years.",
"3-Year Book Growth Rate": "The 3-Year Book Growth Rate measures the compound annual growth rate of a company's book value over the last three years.",
"3-Year Dividend Growth Rate": "The 3-Year Dividend Growth Rate indicates the yearly rate at which a company's dividend payments have increased over the past three years.",
"3-Year EBITDA Growth Rate": "The 3-Year EBITDA Growth Rate is the annual growth rate of earnings before interest, taxes, depreciation, and amortization over the past three years.",
"3-Year EPS without NRI Growth Rate": "The 3-Year EPS without NRI Growth Rate calculates the annual growth rate of earnings per share, excluding non-recurring items, over three years.",
"3-Year FCF Growth Rate": "The 3-Year FCF Growth Rate indicates the annual growth rate of a company's free cash flow over the last three years.",
"3-Year Revenue Growth Rate": "The 3-Year Revenue Growth Rate shows the compound annual growth rate of a company's revenue over a three-year period.",
"5-Day RSI": "The 5-Day RSI is a short-term momentum indicator that compares the magnitude of a stock's recent gains to its recent losses.",
"5-Year Yield-on-Cost %": "The 5-Year Yield-on-Cost % calculates the annual dividend yield of a stock based on the original purchase price, averaged over five years.",
"6-1 Month Momentum %": "The 6-1 Month Momentum % represents the percentage change in a stock's price from six months ago to one month ago.",
"9-Day RSI": "The 9-Day RSI is a technical indicator that measures the speed and change of stock price movements.",
"Altman Z-Score": "The Altman Z-Score predicts the probability of a company entering bankruptcy within the next two years.",
"Beneish M-Score": "The Beneish M-Score is a mathematical model that uses financial ratios to identify whether a company has manipulated its earnings.",
"Cash Ratio": "The cash ratio is a liquidity ratio that measures a company's ability to repay short-term debt with cash and cash equivalents.",
"Cash-To-Debt": "The Cash-To-Debt ratio measures the financial strength of a company by comparing its cash and cash equivalents to its total debt.",
"ClosePrice": "ClosePrice refers to the price at which a stock last traded during a regular trading session.",
"Current Ratio": "The current ratio is a liquidity ratio that measures a company's ability to pay short-term obligations or those due within one year.",
"Days Inventory": "Days Inventory indicates the average number of days a company holds its inventory before selling it.",
"Days Payable": "Days Payable represents the average number of days a company takes to pay its invoices from trade creditors.",
"Days Sales Outstanding": "Days Sales Outstanding measures the average number of days it takes a company to collect payment after a sale.",
"Debt-to-EBITDA": "The Debt-to-EBITDA ratio measures a company's financial leverage and is calculated by dividing its debt by earnings before interest, taxes, depreciation, and amortization.",
"Debt-to-Equity": "The Debt-to-Equity ratio indicates the relative proportion of shareholders' equity and debt used to finance a company's assets.",
"Distress": "Distress refers to a situation where a company is unable to meet its financial obligations.",
"Dividend Payout Ratio": "The Dividend Payout Ratio shows the percentage of earnings distributed to shareholders in the form of dividends.",
"Dividend Yield %": "Dividend Yield % is a financial ratio that shows how much a company pays out in dividends each year relative to its stock price.",
"EV-to-EBIT": "The EV-to-EBIT ratio is a valuation metric that compares the worth of a company to its earnings before interest and taxes.",
"EV-to-EBITDA": "The EV-to-EBITDA ratio is a measure of a company's value including debt, compared to its earnings before interest, taxes, depreciation, and amortization.",
"EV-to-FCF": "The EV-to-FCF ratio compares a company's enterprise value to its free cash flow.",
"EV-to-Forward-EBIT": "The EV-to-Forward-EBIT ratio estimates a company's valuation against its projected earnings before interest and taxes for the upcoming period.",
"EV-to-Forward-EBITDA": "The EV-to-Forward-EBITDA ratio is a valuation measure comparing the enterprise value of a company to its expected EBITDA for a future period.",
"EV-to-Forward-Revenue": "The EV-to-Forward-Revenue ratio values a company by comparing its enterprise value to its forecasted revenue.",
"EV-to-Revenue": "The EV-to-Revenue ratio measures the value of a company in terms of its total market capitalization plus debt against its sales or revenue.",
"Earnings Yield (Greenblatt) %": "The Earnings Yield (Greenblatt) % is calculated by taking the inverse of the price-to-earnings ratio, representing the return an investment would yield if the company paid out all of its earnings.",
"Equity-to-Asset": "The Equity-to-Asset ratio measures the percentage of assets financed by owners' equity.",
"FCF Margin %": "The FCF Margin % measures the percentage of free cash flow relative to total revenue.",
"FCF Yield %": "The FCF Yield % is a financial ratio that compares the free cash flow per share a company is expected to earn against its market value per share.",
"Forward Dividend Yield %": "The Forward Dividend Yield % is an estimate of the dividend yield for the next twelve months.",
"Forward PE Ratio": "The Forward PE Ratio is a valuation metric that uses projected earnings to calculate the PE ratio, rather than past earnings.",
"Forward Rate of Return (Yacktman) %": "The Forward Rate of Return (Yacktman) % estimates the expected rate of return for a stock based on normalized free cash flow and book value growth.",
"Future 3-5Y EPS without NRI Growth Rate": "The Future 3-5Y EPS without NRI Growth Rate is an estimate of the annual EPS growth over the next 3-5 years, excluding non-recurring items.",
"Future 3-5Y Total Revenue Growth Rate": "The Future 3-5Y Total Revenue Growth Rate is a projection of a company's revenue growth annually over the next three to five years.",
"GFValue": "GFValue represents the intrinsic value of a stock calculated by GuruFocus based on its historical ratios, past performance, and future earnings.",
"Gross Margin %": "Gross Margin % is the percentage of total sales revenue that a company retains after incurring the direct costs associated with producing the goods it sells.",
"Interest Coverage": "The Interest Coverage ratio is a measure of a company's ability to meet its interest payments.",
"Manipulator": "Manipulator denotes an entity or company that is involved in market manipulation or financial statement manipulation.",
"N/A": "N/A stands for not applicable, indicating that certain data or information does not apply or is not available in a particular context.",
"Net Margin %": "Net Margin % shows the percentage of net income derived from total sales revenue.",
"Not Manipulator": "Not Manipulator suggests that there is no evidence to indicate that a company is involved in any manipulation of its financial statements.",
"Operating Margin %": "Operating Margin % measures the proportion of a company's revenue that is left over after paying for variable costs of production.",
"PB Ratio": "The PB Ratio, or price-to-book ratio, compares a company's market value to its book value.",
"PE Ratio": "The PE Ratio, or price-to-earnings ratio, indicates the dollar amount an investor can expect to invest in a company in order to receive one dollar of that company's earnings.",
"PE Ratio without NRI": "The PE Ratio without NRI, or price-to-earnings ratio excluding non-recurring items, measures the stock price relative to its earnings without considering one-time events.",
"PEG Ratio": "The PEG Ratio, or price/earnings to growth ratio, is a stock's price-to-earnings ratio divided by the growth rate of its earnings.",
"PS Ratio": "The PS Ratio, or price-to-sales ratio, is a valuation metric that compares a company's stock price to its revenues.",
"Piotroski F-Score": "The Piotroski F-Score is a score between 0 to 9 used to assess the financial strength of a company based on nine accounting-based criteria.",
"Price-to-DCF (Earnings Based)": "Price-to-DCF (Earnings Based) is a valuation metric that compares a company's price to its discounted future earnings.",
"Price-to-DCF (FCF Based)": "Price-to-DCF (FCF Based) is a valuation metric comparing a company's current stock price to its discounted predicted free cash flows.",
"Price-to-FFO": "Price-to-FFO is a real estate valuation measure that compares the price of a real estate investment trust (REIT) to its funds from operations.",
"Price-to-Free-Cash-Flow": "Price-to-Free-Cash-Flow is a ratio used to compare a company's market value to its free cash flow.",
"Price-to-Graham-Number": "Price-to-Graham-Number is a valuation metric that compares a stock's current price to Benjamin Graham's intrinsic value.",
"Price-to-Median-PS-Value": "Price-to-Median-PS-Value is a valuation metric comparing a stock's price with its industry median price-to-sales ratio.",
"Price-to-Net-Cash": "Price-to-Net-Cash compares a company's market cap to its net cash, indicating how many times a company can be bought with its net cash.",
"Price-to-Net-Current-Asset-Value": "Price-to-Net-Current-Asset-Value is a valuation metric that compares the market value of a company to its net current asset value.",
"Price-to-Operating-Cash-Flow": "Price-to-Operating-Cash-Flow is a ratio that measures the value of a company's stock price compared to its operating cash flow per share.",
"Price-to-Owner-Earnings": "Price-to-Owner-Earnings is a valuation ratio that compares a stock's price with the owner's earnings available to shareholders.",
"Price-to-Peter-Lynch-Fair-Value": "Price-to-Peter-Lynch-Fair-Value compares a company's stock price to the fair value as estimated by the Peter Lynch value formula.",
"Price-to-Projected-FCF": "Price-to-Projected-FCF compares the current stock price to the forecasted future free cash flow of the company.",
"Price-to-Tangible-Book": "Price-to-Tangible-Book is a ratio that compares the market value of a company's shares to its tangible book value.",
"Quick Ratio": "The Quick Ratio is a measure of a company's ability to meet its short-term obligations with its most liquid assets.",
"ROA %": "ROA %, or return on assets, measures how efficiently a company uses its assets to generate profit.",
"ROC (Joel Greenblatt) %": "ROC (Joel Greenblatt) % is the return on capital as defined by investor Joel Greenblatt, which considers earnings before interest and taxes against tangible capital employed.",
"ROCE %": "ROCE %, or return on capital employed, measures a company's profitability and the efficiency with which its capital is employed.",
"ROE %": "ROE %, or return on equity, measures the financial return on investment for the company's shareholders.",
"ROIC": "ROIC, or return on invested capital, measures the percentage return that a company earns on the capital invested in its business.",
"ROIC %": "ROIC % is similar to ROIC, providing the return percentage on the capital invested by the company.",
"Safe": "Safe denotes a low-risk status often related to investment or financial conditions.",
"Shareholder Yield %": "Shareholder Yield % combines dividend yield, share repurchases, and debt reduction to determine the total return to shareholders.",
"Shiller PE Ratio": "The Shiller PE Ratio is a valuation measure that uses real earnings over a 10-year period to smooth out fluctuations in corporate profits.",
"WACC": "WACC, or Weighted Average Cost of Capital, is the average rate of return a company is expected to pay its security holders to finance its assets.",
"WACC vs ROIC": "WACC vs ROIC is a comparison between a company's weighted average cost of capital and its return on invested capital to determine value creation or destruction.",
"Years of Profitability over Past 10-Year": "Years of Profitability over Past 10-Year measures how many years a company has been profitable within the last decade.",
"Market Capitalization": "Market Capitalization represents the total market value of a company's outstanding shares.",
"Industry": "Industry refers to a group of companies that are related based on their primary business activities.",
"Sector": "Sector denotes a large segment of the economy in which businesses share the same or a related product or service."
}